[package]
name = "uluru"
version = "0.4.0"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
description = "A simple, fast, LRU cache implementation"
repository = "https://github.com/servo/uluru"
keywords = ["cache", "linkedlist", "array", "no_std"]
categories = ["data-structures", "no-std"]
readme = "README.md"

[lib]
name = "uluru"
path = "lib.rs"

[dependencies]
arrayvec = { version = "0.5", default-features = false } # public dependency
